version: "3.9"

services:
  api:
    build: .
    container_name: kasparro-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/etl_db
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:15
    container_name: kasparro-postgres
    environment:
      POSTGRES_DB: etl_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
